---

name: DolyameSDKUsageDemo_Partners
settings:
  DEVELOPMENT_TEAM: 7PZA53CVLX
  ENABLE_BITCODE: false

targets:
  DolyameSDKUsageDemo:
    scheme: {}
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: [DolyameSDKUsageDemo]
    settings:
      base:
        MARKETING_VERSION: 2.2.0
        CURRENT_PROJECT_VERSION: 1
        BUILD_LIBRARY_FOR_DISTRIBUTION: true
        PRODUCT_BUNDLE_IDENTIFIER: com.mc.walker.bnpl-mobile-dev-platform.DolyameSDK
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: 7PZA53CVLX
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: "match Development com.mc.walker.bnpl-mobile-dev-platform.DolyameSDK"
          CODE_SIGN_IDENTITY: "iPhone Developer"
        Release:
          PROVISIONING_PROFILE_SPECIFIER: "match InHouse com.mc.walker.bnpl-mobile-dev-platform.DolyameSDK"
          CODE_SIGN_IDENTITY: "iPhone Distribution"
